services:
  app:
    build: ./
    restart: always
    ports:
      - 8000:8080
    depends_on:
      - db

  db:
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
