services:
  app:
    build: ./
    depends_on:
      - db
    ports:
      - 8000:8080

  db:
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3308:3306
    #    command: --init-file /data/application/init.sql
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql


